name: Deploy Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ 必须：允许 Action 修改仓库内容
    steps:
      - name: 自动部署网站
        uses: naiyniB/WorkFlow-Unzip-Deploy@xxx
        with:
          File_directory: "public"
          exclude_files: "CNAME|.nojekyll"
          delete_zip_directory: "true"